---
- name: Add PHP Repositories
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present update_cache=yes

- name : Install Base PHP Packages
  yum: name={{packages}} state=present enablerepo=remi-php70 update_cache=yes
  vars:
    packages:
    - php
    - php-opcache
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-mysql
    - php-ldap
    - php-zip
    - php-fileinfo
    - php-gearman

- name: Install Required PHP Packages
  yum: name={{packages}} state=present enablerepo=remi-php73 update_cache=yes
  vars:
    packages:
    - php-redis
    