---
- name: Add Unzip Tools
  yum: name=unzip state=present

- name: Add Wget Tools
  yum: name=wget state=present

- name: Creates Directory
  file: path=/var/www/html/devita state=directory

- name: Extract Wordpress Application
  unarchive:
    src: wordpress.zip
    dest: /var/www/html/devita

- name: Copy Config File
  template:
    src: wp-config.php.j2
    dest: /var/www/html/devita/wp-config.php
    mode: 0755
    
- name: Set Apache Directory Permissions
  file: dest=/var/www/html owner=apache group=apache recurse=yes

- name: Restart Apache Server
  service: name=httpd state=restarted enabled=yes